import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${montserrat.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">
      <Providers>
        <Navbar />
        {/* <main className="flex grow"> */}
        {children}
        {/* </main> */}
        <Footer />
      </Providers>
    </body>
    </html>
  );
}